function escapePdfText(input: string) {
  return input.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)')
}

export function buildSimplePdf(lines: string[]) {
  const safeLines = lines.map((line) => escapePdfText(line.slice(0, 110)))

  const commands = ['BT', '/F1 12 Tf', '50 780 Td']
  for (const line of safeLines) {
    commands.push(`(${line}) Tj`)
    commands.push('0 -16 Td')
  }
  commands.push('ET')

  const contentStream = commands.join('\n')

  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',
    `<< /Length ${contentStream.length} >>\nstream\n${contentStream}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ]

  let pdf = '%PDF-1.4\n'
  const offsets: number[] = []

  for (let i = 0; i < objects.length; i++) {
    offsets.push(pdf.length)
    pdf += `${i + 1} 0 obj\n${objects[i]}\nendobj\n`
  }

  const xrefOffset = pdf.length
  pdf += `xref\n0 ${objects.length + 1}\n`
  pdf += '0000000000 65535 f \n'
  for (const offset of offsets) {
    pdf += `${offset.toString().padStart(10, '0')} 00000 n \n`
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`

  return new TextEncoder().encode(pdf)
}

type Party = {
  name: string
  email: string
  phone?: string
}

type Vehicle = {
  _id: string
  make: string
  model: string
  year: number
}

type Transaction = {
  _id: string
  amountNpr: number
}

export function buildBillOfSaleLines(args: {
  vehicle: Vehicle
  buyer: Party
  seller: Party
  transaction: Transaction
}) {
  const stamp = new Date().toISOString().slice(0, 10)
  return [
    'Bill of Sale (Draft)',
    `Date: ${stamp}`,
    `Vehicle: ${args.vehicle.make} ${args.vehicle.model} (${args.vehicle.year})`,
    `VIN/ID Reference: ${args.vehicle._id}`,
    `Buyer: ${args.buyer.name} (${args.buyer.email})`,
    `Seller: ${args.seller.name} (${args.seller.email})`,
    `Sale Amount (NPR): ${args.transaction.amountNpr.toLocaleString('en-US')}`,
    `Transaction Reference: ${args.transaction._id}`,
    'This is an autogenerated draft for record-keeping.',
  ]
}

export function buildOwnershipTransferLines(args: {
  vehicle: Vehicle
  buyer: Party
  seller: Party
  transaction: Transaction
}) {
  const stamp = new Date().toISOString().slice(0, 10)
  return [
    'Ownership Transfer Draft',
    `Date: ${stamp}`,
    `Vehicle: ${args.vehicle.make} ${args.vehicle.model} (${args.vehicle.year})`,
    `Current Owner: ${args.seller.name}`,
    `New Owner: ${args.buyer.name}`,
    `Transaction Reference: ${args.transaction._id}`,
    `Seller Contact: ${args.seller.phone ?? args.seller.email}`,
    `Buyer Contact: ${args.buyer.phone ?? args.buyer.email}`,
    'Final legal validation is required before registration transfer.',
  ]
}
