/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SellersRouteImport } from './routes/sellers'
import { Route as SearchHistoryRouteImport } from './routes/search-history'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NewsRouteImport } from './routes/news'
import { Route as FinancingRouteImport } from './routes/financing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions/index'
import { Route as MessagesIndexRouteImport } from './routes/messages/index'
import { Route as ListingsIndexRouteImport } from './routes/listings/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TransactionsTransactionIdRouteImport } from './routes/transactions/$transactionId'
import { Route as SellerInquiriesRouteImport } from './routes/seller/inquiries'
import { Route as SellerDashboardRouteImport } from './routes/seller/dashboard'
import { Route as SellerApplyRouteImport } from './routes/seller/apply'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as MessagesChatIdRouteImport } from './routes/messages/$chatId'
import { Route as ListingsListingIdRouteImport } from './routes/listings/$listingId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTransactionsRouteImport } from './routes/admin/transactions'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminNewsRouteImport } from './routes/admin/news'
import { Route as SellerListingsIndexRouteImport } from './routes/seller/listings/index'
import { Route as SellerListingsNewRouteImport } from './routes/seller/listings/new'
import { Route as AdminSellersApplicationsRouteImport } from './routes/admin/sellers/applications'
import { Route as AdminListingsPendingRouteImport } from './routes/admin/listings/pending'
import { Route as AdminListingsListingIdRouteImport } from './routes/admin/listings/$listingId'
import { Route as SellerListingsListingIdEditRouteImport } from './routes/seller/listings/$listingId/edit'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SellersRoute = SellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchHistoryRoute = SearchHistoryRouteImport.update({
  id: '/search-history',
  path: '/search-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancingRoute = FinancingRouteImport.update({
  id: '/financing',
  path: '/financing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIndexRoute = ListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsTransactionIdRoute =
  TransactionsTransactionIdRouteImport.update({
    id: '/transactions/$transactionId',
    path: '/transactions/$transactionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SellerInquiriesRoute = SellerInquiriesRouteImport.update({
  id: '/seller/inquiries',
  path: '/seller/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerDashboardRoute = SellerDashboardRouteImport.update({
  id: '/seller/dashboard',
  path: '/seller/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerApplyRoute = SellerApplyRouteImport.update({
  id: '/seller/apply',
  path: '/seller/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const MessagesChatIdRoute = MessagesChatIdRouteImport.update({
  id: '/messages/$chatId',
  path: '/messages/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsListingIdRoute = ListingsListingIdRouteImport.update({
  id: '/listings/$listingId',
  path: '/listings/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/admin/transactions',
  path: '/admin/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/admin/news',
  path: '/admin/news',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerListingsIndexRoute = SellerListingsIndexRouteImport.update({
  id: '/seller/listings/',
  path: '/seller/listings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerListingsNewRoute = SellerListingsNewRouteImport.update({
  id: '/seller/listings/new',
  path: '/seller/listings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSellersApplicationsRoute =
  AdminSellersApplicationsRouteImport.update({
    id: '/admin/sellers/applications',
    path: '/admin/sellers/applications',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminListingsPendingRoute = AdminListingsPendingRouteImport.update({
  id: '/admin/listings/pending',
  path: '/admin/listings/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminListingsListingIdRoute = AdminListingsListingIdRouteImport.update({
  id: '/admin/listings/$listingId',
  path: '/admin/listings/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerListingsListingIdEditRoute =
  SellerListingsListingIdEditRouteImport.update({
    id: '/seller/listings/$listingId/edit',
    path: '/seller/listings/$listingId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/financing': typeof FinancingRoute
  '/news': typeof NewsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/search-history': typeof SearchHistoryRoute
  '/sellers': typeof SellersRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
  '/messages/$chatId': typeof MessagesChatIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/seller/apply': typeof SellerApplyRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/inquiries': typeof SellerInquiriesRoute
  '/transactions/$transactionId': typeof TransactionsTransactionIdRoute
  '/admin/': typeof AdminIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/admin/listings/$listingId': typeof AdminListingsListingIdRoute
  '/admin/listings/pending': typeof AdminListingsPendingRoute
  '/admin/sellers/applications': typeof AdminSellersApplicationsRoute
  '/seller/listings/new': typeof SellerListingsNewRoute
  '/seller/listings/': typeof SellerListingsIndexRoute
  '/seller/listings/$listingId/edit': typeof SellerListingsListingIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/financing': typeof FinancingRoute
  '/news': typeof NewsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/search-history': typeof SearchHistoryRoute
  '/sellers': typeof SellersRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
  '/messages/$chatId': typeof MessagesChatIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/seller/apply': typeof SellerApplyRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/inquiries': typeof SellerInquiriesRoute
  '/transactions/$transactionId': typeof TransactionsTransactionIdRoute
  '/admin': typeof AdminIndexRoute
  '/listings': typeof ListingsIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/admin/listings/$listingId': typeof AdminListingsListingIdRoute
  '/admin/listings/pending': typeof AdminListingsPendingRoute
  '/admin/sellers/applications': typeof AdminSellersApplicationsRoute
  '/seller/listings/new': typeof SellerListingsNewRoute
  '/seller/listings': typeof SellerListingsIndexRoute
  '/seller/listings/$listingId/edit': typeof SellerListingsListingIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/financing': typeof FinancingRoute
  '/news': typeof NewsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/search-history': typeof SearchHistoryRoute
  '/sellers': typeof SellersRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
  '/messages/$chatId': typeof MessagesChatIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/seller/apply': typeof SellerApplyRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/inquiries': typeof SellerInquiriesRoute
  '/transactions/$transactionId': typeof TransactionsTransactionIdRoute
  '/admin/': typeof AdminIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/admin/listings/$listingId': typeof AdminListingsListingIdRoute
  '/admin/listings/pending': typeof AdminListingsPendingRoute
  '/admin/sellers/applications': typeof AdminSellersApplicationsRoute
  '/seller/listings/new': typeof SellerListingsNewRoute
  '/seller/listings/': typeof SellerListingsIndexRoute
  '/seller/listings/$listingId/edit': typeof SellerListingsListingIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/dashboard'
    | '/financing'
    | '/news'
    | '/profile'
    | '/search-history'
    | '/sellers'
    | '/sign-in'
    | '/sign-up'
    | '/admin/news'
    | '/admin/reviews'
    | '/admin/transactions'
    | '/admin/users'
    | '/listings/$listingId'
    | '/messages/$chatId'
    | '/news/$slug'
    | '/seller/apply'
    | '/seller/dashboard'
    | '/seller/inquiries'
    | '/transactions/$transactionId'
    | '/admin/'
    | '/listings/'
    | '/messages/'
    | '/transactions/'
    | '/admin/listings/$listingId'
    | '/admin/listings/pending'
    | '/admin/sellers/applications'
    | '/seller/listings/new'
    | '/seller/listings/'
    | '/seller/listings/$listingId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/dashboard'
    | '/financing'
    | '/news'
    | '/profile'
    | '/search-history'
    | '/sellers'
    | '/sign-in'
    | '/sign-up'
    | '/admin/news'
    | '/admin/reviews'
    | '/admin/transactions'
    | '/admin/users'
    | '/listings/$listingId'
    | '/messages/$chatId'
    | '/news/$slug'
    | '/seller/apply'
    | '/seller/dashboard'
    | '/seller/inquiries'
    | '/transactions/$transactionId'
    | '/admin'
    | '/listings'
    | '/messages'
    | '/transactions'
    | '/admin/listings/$listingId'
    | '/admin/listings/pending'
    | '/admin/sellers/applications'
    | '/seller/listings/new'
    | '/seller/listings'
    | '/seller/listings/$listingId/edit'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/dashboard'
    | '/financing'
    | '/news'
    | '/profile'
    | '/search-history'
    | '/sellers'
    | '/sign-in'
    | '/sign-up'
    | '/admin/news'
    | '/admin/reviews'
    | '/admin/transactions'
    | '/admin/users'
    | '/listings/$listingId'
    | '/messages/$chatId'
    | '/news/$slug'
    | '/seller/apply'
    | '/seller/dashboard'
    | '/seller/inquiries'
    | '/transactions/$transactionId'
    | '/admin/'
    | '/listings/'
    | '/messages/'
    | '/transactions/'
    | '/admin/listings/$listingId'
    | '/admin/listings/pending'
    | '/admin/sellers/applications'
    | '/seller/listings/new'
    | '/seller/listings/'
    | '/seller/listings/$listingId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  FinancingRoute: typeof FinancingRoute
  NewsRoute: typeof NewsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SearchHistoryRoute: typeof SearchHistoryRoute
  SellersRoute: typeof SellersRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ListingsListingIdRoute: typeof ListingsListingIdRoute
  MessagesChatIdRoute: typeof MessagesChatIdRoute
  SellerApplyRoute: typeof SellerApplyRoute
  SellerDashboardRoute: typeof SellerDashboardRoute
  SellerInquiriesRoute: typeof SellerInquiriesRoute
  TransactionsTransactionIdRoute: typeof TransactionsTransactionIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ListingsIndexRoute: typeof ListingsIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
  AdminListingsListingIdRoute: typeof AdminListingsListingIdRoute
  AdminListingsPendingRoute: typeof AdminListingsPendingRoute
  AdminSellersApplicationsRoute: typeof AdminSellersApplicationsRoute
  SellerListingsNewRoute: typeof SellerListingsNewRoute
  SellerListingsIndexRoute: typeof SellerListingsIndexRoute
  SellerListingsListingIdEditRoute: typeof SellerListingsListingIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sellers': {
      id: '/sellers'
      path: '/sellers'
      fullPath: '/sellers'
      preLoaderRoute: typeof SellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-history': {
      id: '/search-history'
      path: '/search-history'
      fullPath: '/search-history'
      preLoaderRoute: typeof SearchHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financing': {
      id: '/financing'
      path: '/financing'
      fullPath: '/financing'
      preLoaderRoute: typeof FinancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/': {
      id: '/listings/'
      path: '/listings'
      fullPath: '/listings/'
      preLoaderRoute: typeof ListingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/$transactionId': {
      id: '/transactions/$transactionId'
      path: '/transactions/$transactionId'
      fullPath: '/transactions/$transactionId'
      preLoaderRoute: typeof TransactionsTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/inquiries': {
      id: '/seller/inquiries'
      path: '/seller/inquiries'
      fullPath: '/seller/inquiries'
      preLoaderRoute: typeof SellerInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/dashboard': {
      id: '/seller/dashboard'
      path: '/seller/dashboard'
      fullPath: '/seller/dashboard'
      preLoaderRoute: typeof SellerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/apply': {
      id: '/seller/apply'
      path: '/seller/apply'
      fullPath: '/seller/apply'
      preLoaderRoute: typeof SellerApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/messages/$chatId': {
      id: '/messages/$chatId'
      path: '/messages/$chatId'
      fullPath: '/messages/$chatId'
      preLoaderRoute: typeof MessagesChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$listingId': {
      id: '/listings/$listingId'
      path: '/listings/$listingId'
      fullPath: '/listings/$listingId'
      preLoaderRoute: typeof ListingsListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/admin/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/admin/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/listings/': {
      id: '/seller/listings/'
      path: '/seller/listings'
      fullPath: '/seller/listings/'
      preLoaderRoute: typeof SellerListingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/listings/new': {
      id: '/seller/listings/new'
      path: '/seller/listings/new'
      fullPath: '/seller/listings/new'
      preLoaderRoute: typeof SellerListingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sellers/applications': {
      id: '/admin/sellers/applications'
      path: '/admin/sellers/applications'
      fullPath: '/admin/sellers/applications'
      preLoaderRoute: typeof AdminSellersApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/listings/pending': {
      id: '/admin/listings/pending'
      path: '/admin/listings/pending'
      fullPath: '/admin/listings/pending'
      preLoaderRoute: typeof AdminListingsPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/listings/$listingId': {
      id: '/admin/listings/$listingId'
      path: '/admin/listings/$listingId'
      fullPath: '/admin/listings/$listingId'
      preLoaderRoute: typeof AdminListingsListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/listings/$listingId/edit': {
      id: '/seller/listings/$listingId/edit'
      path: '/seller/listings/$listingId/edit'
      fullPath: '/seller/listings/$listingId/edit'
      preLoaderRoute: typeof SellerListingsListingIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  FinancingRoute: FinancingRoute,
  NewsRoute: NewsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SearchHistoryRoute: SearchHistoryRoute,
  SellersRoute: SellersRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ListingsListingIdRoute: ListingsListingIdRoute,
  MessagesChatIdRoute: MessagesChatIdRoute,
  SellerApplyRoute: SellerApplyRoute,
  SellerDashboardRoute: SellerDashboardRoute,
  SellerInquiriesRoute: SellerInquiriesRoute,
  TransactionsTransactionIdRoute: TransactionsTransactionIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ListingsIndexRoute: ListingsIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
  AdminListingsListingIdRoute: AdminListingsListingIdRoute,
  AdminListingsPendingRoute: AdminListingsPendingRoute,
  AdminSellersApplicationsRoute: AdminSellersApplicationsRoute,
  SellerListingsNewRoute: SellerListingsNewRoute,
  SellerListingsIndexRoute: SellerListingsIndexRoute,
  SellerListingsListingIdEditRoute: SellerListingsListingIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
